services:
  - type: web
    name: my-streamlit-app   # غيّر الاسم زي ما تحب
    env: python
    plan: free               # تقدر تغيّرها إلى starter أو غيره
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
